apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    application: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      application: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: termine
        - name: POSTGRES_PASSWORD
          value: termine_pw!
        image: postgres:11
        name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-claim0
        ports:
          - containerPort: 5432
      restartPolicy: Always
      volumes:
      - name: postgres-claim0
        persistentVolumeClaim:
          claimName: postgres-claim0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-claim0
  name: postgres-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: postgres
  name: postgres
spec:
  ports:
    - name: "tcp"
      port: 5432
      targetPort: 5432
  selector:
    application: postgres