name: Backend-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the backend tests
      run: DOCKER_BUILDKIT=1 docker build . --progress=plain --file Dockerfile --target=tester --tag tester && docker run tester
